// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SamplePipeDelimiter.Contexts;

#nullable disable

namespace SamplePipeDelimiter.Migrations
{
    [DbContext(typeof(UlsDbContext))]
    partial class UlsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SamplePipeDelimiter.Models.PubAccCO", b =>
                {
                    b.Property<string>("RecordType")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("record_type")
                        .HasColumnOrder(0);

                    b.Property<string>("CallSign")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("callsign")
                        .HasColumnOrder(3);

                    b.Property<string>("CommentDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("comment_date")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description")
                        .HasColumnOrder(5);

                    b.Property<string>("StatusCode")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status_code")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("status_date")
                        .HasColumnOrder(7);

                    b.Property<string>("UlsFileNum")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("uls_file_num")
                        .HasColumnOrder(2);

                    b.Property<decimal>("UniqueSystemIdentifier")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)")
                        .HasColumnName("unique_system_identifier")
                        .HasColumnOrder(1);

                    b.HasKey("RecordType");

                    b.ToTable("pubacc_co", "main");
                });
#pragma warning restore 612, 618
        }
    }
}
